### PR TITLE
Splits landing page sections to views so they can be overridden if necessary

### PR DESCRIPTION
**Pull request by juho-jaakkola**
This allows plugins to override individual parts of the landing page, and also simplifies the structure of the layout file.

### CODE REVIEW

**Comment by demyxco** [comment]
Nice!

**Comment by demyxco** [comment]
I'm thinking of having the Landr settings moved to the actual index page. What do you think @juho-jaakkola ?

**Comment by juho-jaakkola** [comment]
Do you mean that `elgg_get_plugin_setting()` calls would be on the index page and not in the view?

**Comment by demyxco** [comment]
No, I was referring to have the Landr settings be placed in the index page and updated within the DOM, then the settings saved via ajax call.

**Comment by juho-jaakkola** [comment]
I see. Open a new issue for it and document your current plans there. We can then discuss it in more detail.

**Pull request merged**
